### ISSUE TITLE
Some file are missing in Assets Folder

### ISSUE THREAD

**Issue by mendezdl** [hupo376787/A-Beautiful-UWP-Frame#1]
Facebook512.png,
Gift300.png
paypal-new-logo.png
QQChat512.png
Twitter512.png
WeChat512.png
Weibo512.png
WeiboChat512.png
Yixin512.png
微信+.png
支付宝+.png

**Comment by hupo376787** [comment]
Hi, you can delete them in the Assets, or find some files instead. This does not affect the final result.
